import { deleteValue, getValue, setValue } from './lang/deepValue.js';
import { deleteVar, newVar } from './lang/simpleVar.js';
import { isLess, logicAnd, isEqual, isGreater, logicNot, logicOr } from './lang/booleanLogic.js';
import { ifElse } from './lang/ifElse.js';
import { forEach } from './lang/forEach.js';
import { newSuperStruct } from './lang/superStruct.js';
import { newSuperArray } from './lang/superArray.js';
export declare const sprogFuncs: {
    jsExp: import("./scope.js").SprogFn;
    simpleCall: import("./scope.js").SprogFn;
    ifElse: typeof ifElse;
    forEach: typeof forEach;
    getValue: typeof getValue;
    setValue: typeof setValue;
    deleteValue: typeof deleteValue;
    newVar: typeof newVar;
    deleteVar: typeof deleteVar;
    logicAnd: typeof logicAnd;
    logicOr: typeof logicOr;
    logicNot: typeof logicNot;
    isEqual: typeof isEqual;
    isGreater: typeof isGreater;
    isLess: typeof isLess;
    callSuperFunc: import("./scope.js").SprogFn;
    newSuperFunc: import("./scope.js").SprogFn;
    newSuperStruct: typeof newSuperStruct;
    newSuperArray: typeof newSuperArray;
};
